### ISSUE TITLE
64 bit compile

### ISSUE THREAD

**Issue by 272development** [ivere27/dorypuppy#2]
Due to android playstore restrictions, we need 64 bit library files.

Can you update your code to produce the 64 bit libs too?  You have prebuilt imports and I am not sure of the source.

Thank you greatly!

**Comment by 272development** [comment]
Are you still maintaining this project?

**Comment by ivere27** [comment]
thanks for using the library.
i just uploaded the arm64 libuv.so and tested with my dorynode app.
https://github.com/ivere27/dorypuppy/commit/e0f8c6872f7e33fd7d1e25153027b3b6d2d81b1a

by the way, if you are using andorid 11 then you need to put the binary to jnilibs as libXXX.so
context.getApplicationInfo().nativeLibraryDir 
ref : https://developer.android.com/about/versions/10/behavior-changes-10#execute-permission
